[package]
name = "webview_sys"
version = "0.1.0"
authors = ["oliver giersch"]
build = "build.rs"
links = "webview"

[lib]
name = "webview_sys"
path = "src/lib.rs"

[dependencies]

[build-dependencies]
cc = "*"
pkg-config = "*"