[package]
name = "webview_ffi"
version = "0.1.0"
authors = ["oliver <oliver.giersch@googlemail.com>"]
build = "build.rs"
#links = "webview"

[lib]
name = "webview_ffi"
path = "src/lib.rs"

[dependencies]

[build-dependencies]
cc = "*"
pkg-config = "*"